resolver: lts-5.14

packages:
- 'fn'
- 'fn-extra'
- 'example'
- location:
    git: https://github.com/positiondev/larceny
    commit: 15b97c95447b8faeccb708d9541804bd2c616f46
  extra-dep: true

extra-deps:
- wai-util-0.8
- http-accept-0.2
- logging-3.0.2
- wai-session-clientsession-0.1
- cereal-text-0.1.0.1
- directory-1.2.6.3

flags: {}

extra-package-dbs: []
